version: '2'
services:
  mysql_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthmonitor
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret